🐛 bugfix module import error and type error
ERROR: "ModuleNotFoundError: No module named 'algotraders.brokers.fyers.py'; 'algotraders.brokers.fyers' is not a package"
- registry.py L128 calls importlib.import_module(...) which expects dot-seperated module path with no file extension

ERROR: TypeError: FyersAPI.fetchData() missing 1 required positional argument: 'self'
- asyncyWrapper (and syncWrapper) both capture self correctly but the call to "func(*args, **kwargs)" drops self entirely
- passed self explicitly to the wrapper function call [await] func(self, ...) to both the wrapper function in @requireLogin

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>